---

blog_nginx_templates:
  - src: nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  - src: nginx/htpasswd
    dest: /etc/nginx/.htpasswd
    owner: root
    group: root
    mode: "0644"
  - src: nginx/logrotate.conf
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: "0644"

blog_nginx_linked_templates:
  - src: nginx/blog.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: "0644"

blog_static_directory: "/var/www/blog"

blog_statistics_directory: "/var/www/blogstats"

blog_github_url: https://github.com/mcorbin/blog/tarball/master

blog_nginx_port: 8200

meuse_static_directory: "/var/www/meuse"

meuse_github_url: https://github.com/mcorbin/meuse-website/tarball/master
