---
haproxy_configuration_templates:
  - src: haproxy/haproxy.cfg.j2
    dest: 01_haproxy.cfg
  - src: haproxy/frontend.j2
    dest: 02_frontend.cfg
  - src: haproxy/blog.j2
    dest: 03_blog.cfg
  - src: haproxy/meuse.j2
    dest: 03_meuse.cfg
  - src: haproxy/tour.j2
    dest: 03_tour.cfg
  - src: haproxy/fishing.j2
    dest: 03_fishing.cfg
  - src: haproxy/cabourotte.j2
    dest: 04_cabourotte.cfg
  - src: haproxy/commentator.j2
    dest: 04_commentator.cfg

haproxy_cert_directory: "/etc/ssl/mcorbin.fr"
haproxy_cert_path: "{{ haproxy_cert_directory }}/mcorbin.fr.pem"

haproxy_letsencrypt_path: "/etc/letsencrypt/live/mcorbin.fr/"

haproxy_debian_backports_enabled: false
frontend_eip: 159.100.242.232
