---
- name: install haproxy package
  become: true
  apt:
    name: "{{ haproxy_package }}"
    state: present
    force: "{{ haproxy_force_install }}"
    default_release: "{{ haproxy_debian_distribution }}-backports"
  notify: haproxy | restart
