---
galaxy_info:
  author: Mathieu Corbin
  description: HAProxy for Debian
  license: GPLv2
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
