---
- hosts: blog
  vars_files:
    - password.yml
  roles:
    - role: nginx
      vars:
        nginx_templates: "{{ blog_nginx_templates }}"
        nginx_linked_templates: "{{ blog_nginx_linked_templates }}"
      tags: nginx
  post_tasks:
    # TODO : replace this by CD tool
    - name: create blog static directory
      become: true
      file:
        path: "{{ blog_static_directory }}"
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: create meuse static directory
      become: true
      file:
        path: "{{ meuse_static_directory }}"
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: create blog statistics directory
      become: true
      file:
        path: "{{ blog_statistics_directory }}"
        state: directory
        owner: root
        group: root
        mode: 0755
    # not idempotent and hacky but will be replaced soon by continuous deploymeny
    # tool.
    # blog
    - name: create tmp dir for blog
      become: true
      file:
        path: /tmp/blog
        state: directory
        owner: root
        group: root
        mode: "0644"
    - name: download and unarchive blog archive
      become: true
      unarchive:
        src: "{{ blog_github_url }}"
        dest: /tmp/blog
        remote_src: yes
        extra_opts: "--strip-components=1"
    - name: remove current blog dir content
      become: true
      shell: "rm -rf {{ blog_static_directory }}/*"
    - name: copy blog
      become: true
      shell: "cp -r /tmp/blog/resources/public/* {{ blog_static_directory }}/"
    - name: remove tmp dir for blog
      become: true
      file:
        path: /tmp/blog
        state: absent
  tags: techblog

- hosts: blog
  tasks:
    - name: "install goaccess"
      become: true
      apt:
        name: goaccess
        state: present
      tags: goaccess
    - name: "template goaccess config"
      become: true
      template:
        src: "goaccess/goaccess.conf"
        dest: "/etc/goaccess.conf"
        owner: root
        group: root
        mode: 0644
      tags: goaccess
    - name: "template goaccess script"
      become: true
      template:
        src: "goaccess/cron.sh"
        dest: "/usr/bin/goaccesscron"
        owner: root
        group: root
        mode: 0750
      tags: goaccess
    - name: add goaccess crontab
      become: true
      cron:
        name: "goaccess"
        job: "/usr/bin/goaccesscron"
        minute: 50
        hour: 23
      tags: goaccess

# meuse deployment
- hosts: blog
  tasks:
    - name: create tmp dir for meuse
      become: true
      file:
        path: /tmp/meuse
        state: directory
        owner: root
        group: root
        mode: "0644"
    - name: download and unarchive meuse archive
      become: true
      unarchive:
        src: "{{ meuse_github_url }}"
        dest: /tmp/meuse
        remote_src: yes
        extra_opts: "--strip-components=1"
    - name: remove current meuse dir content
      become: true
      shell: "rm -rf {{ meuse_static_directory }}/*"
    - name: copy meuse
      become: true
      shell: "cp -r /tmp/meuse/public/* {{ meuse_static_directory }}/"
    - name: remove tmp dir for meuse
      become: true
      file:
        path: /tmp/meuse
        state: absent
  tags: meuse
