---
- hosts: base
  become: true
  tasks:
    - name: apt | update cache
      become: true
      apt:
        update_cache: yes
    - name: apt upgrade
      become: true
      apt:
        upgrade: dist
    - name: install default packages
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ debian_default_packages }}"
