---
- hosts: base
  gather_facts: true
  tags: always

- import_playbook: debian.yml
  tags: debian

- hosts: base
  roles:
    - role: ssh
      tags: ssh

- hosts: mirabelle
  roles:
    - role: java
      tags: java
    - role: mirabelle
      tags: mirabelle
