- name: ssh
  src: git+ssh://git@github.com/mcorbin/ssh-ansible-role
  scm: git
  version: "master"

- name: java
  src: git+ssh://git@github.com/mcorbin/java-ansible-role
  scm: git
  version: "master"

