N=1

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define "haproxy9" do |haproxy|
    haproxy.vm.synced_folder "..", "/vagrant", :disabled => "true"
    haproxy.vm.hostname = "haproxy9"
    haproxy.vm.box = "debian/stretch64"
    haproxy.vm.provider :libvirt do |domain|
      domain.memory = 512
      domain.cpus = 1
    end
  end

  config.vm.define "haproxy8" do |haproxy|
    haproxy.vm.synced_folder "..", "/vagrant", :disabled => "true"
    haproxy.vm.hostname = "haproxy8"
    haproxy.vm.box = "debian/jessie64"
    haproxy.vm.provider :libvirt do |domain|
      domain.memory = 512
      domain.cpus = 1
    end
    haproxy.vm.provision :shell do |shell|
      shell.inline = "apt-get update; apt-get install ca-certificates -y"
    end

    haproxy.vm.provision :ansible do |ansible|
      ansible.limit = "all"

      ansible.playbook = "./playbook.yml"
      ansible.host_key_checking = "False"
    end
  end
end
