---
- name: haproxy | restart
  become: true
  service:
    name: haproxy
    state: restarted

- name: haproxy | reload
  become: true
  service:
    name: haproxy
    state: reloaded

- name: apt | update cache
  become: true
  apt:
    update_cache: yes
